### ISSUE TITLE
Themes download fails

### ISSUE THREAD

**Issue by LeiZeng** [WestpacCXTeam/Starter-Pack#20]
Hi,
The curl task just fail when downloading the theme.zip, and I just check the link http://thewestpacgroup-gel.io/GUI/BOM/downloads/theme.zip
Which is not available any more, can you please have a look? Because I can't finish setup.

**Comment by dominikwilkowski** [comment]
Hey @LeiZeng 

Thanks for reporting this. The new url is:
- http://gel.westpacgroup.com.au/GUI/legacy/v1.1.2/BOM/downloads/theme.zip
- http://gel.westpacgroup.com.au/GUI/legacy/v1.1.2/BOM/downloads/theme.zip
- http://gel.westpacgroup.com.au/GUI/legacy/v1.1.2/BOM/downloads/theme.zip
