### ISSUE TITLE
How to get NPM working through proxy

### ISSUE THREAD

**Issue by astrotim** [WestpacCXTeam/Starter-Pack#21]
This gets NPM working through the Westpac proxy
```
npm config set proxy http://<L_ID>:<password>@intproxy80.prod.srv.westpac.com.au
```
Substitute `<L_ID>` and `<password>` with your details respectively. *Note:* the password must be URL encoded. For example, a `!` must be entered as `%21`.

The setting is written to the `<home-dir>/.npmrc` file, so you can check it there or use:
```
npm config get proxy
```

**Comment by oksushi** [comment]
:+1: 

This needs to go on Slack as a pinned post.

**Comment by dominikwilkowski** [comment]
This is great. Thanks @astrotim
